### ISSUE TITLE
[ Bug ] Opening the gallery from the camera app disables password protection.

### ISSUE THREAD

**Issue by onegladius** [FossifyOrg/Camera#10]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Camera/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Camera/issues) or [closed](https://github.com/FossifyOrg/Camera/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Camera/discussions) or [closed](https://github.com/FossifyOrg/Camera/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Camera/blob/master/CONTRIBUTING.md).

### Affected app version

5.7.2 - latest SMT release

### Affected Android/Custom ROM version

Android 10 ( Stock )

### Affected device model

Motorola moto e7 Power

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Open the Fossify Gallery app.
2. Enable "Password protect the whole application" option in the settings.
3. Exit the Gallery app.
4. Open the Camera app.
5. Click on the small icon on the bottom right where the last photo/video taken is shown.

### Expected behavior

When i click on the last picture taken from the camera app it should first ask me to type the PIN code before letting me browse the photos in there.

### Actual behavior

It directly opens the Fossify Gallery app ( which has password protection for then whole app set up , as in the video below ) without asking for the pin.

### Screenshots/Screen recordings

Here

https://github.com/FossifyOrg/Camera/assets/158749828/7057361c-2827-4e15-b142-1df85a028805

### Additional information

• I am opening this issue here even though right now the Fossify Camera app isn't released because the SMT github is dead, and no one responds anymore ; and also because I figured out it this bug will very likely be present in the fork too.

I tested , and this issue also happens in the simple gallery app too.
I store photos/videos taken from my camera in my sd card. I changed the default location ( for the camera app ) to my main storage and the issue still persists whichever Gallery app I open it with, which means it's the Camera app's fault.

It only opens the "Camera" folder, no other one.
If the "Password protect file deletion and moving" option is enabled in the Fossify Gallery app, it respects it.

The only issue the camera has is that it doesn't respect the "Protect protect the whole application" option.

**Comment by Aga-C** [comment]
Please raise this bug in Fossify Gallery, because it's a bigger issue, not only connected to the Camera app. I've tested quickly, and I could reproduce it by opening a photo from any other app.
