### ISSUE TITLE
Support Android's per-app language preferences

### ISSUE THREAD

**Issue by Korb** [FossifyOrg/Camera#32]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Camera/issues) or [closed](https://github.com/FossifyOrg/Camera/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Camera/discussions) or [closed](https://github.com/FossifyOrg/Camera/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Camera/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

The language selector in the app is kind of a legacy UI - now that Android supports per-app language settings (`System Settings` → `System` → `Languages` → `App languages`), we should support that and eventually get rid of the in-app language selector.

### Why do you want this feature?

Unification and following standards.

### Additional information

https://support.google.com/android/answer/12395118
https://developer.android.com/guide/topics/resources/app-languages
https://android-developers.googleblog.com/2022/11/per-app-language-preferences-part-1.html

**Comment by Aga-C** [comment]
We already use the system UI for language change, and we don't plan to remove it from Settings. Not every phone supports changing language from the OS-level, even on Android versions that support it (most notably Xiaomi and OnePlus devices, as stated e.g. here: https://github.com/osmandapp/OsmAnd/issues/16990), and we don't want to make life harder for users of such devices.
